[build]
  command = "npm run build && make build"
  publish = "out"

[[redirects]]
  from = "/webhooks/twitch"
  to = "/.netlify/functions/twitch"
  status = 200

[functions]
  node_bundler = "esbuild"